app_base/app_base/urls.py
from argparse import Namespace
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from app_main import views
from debug_toolbar.toolbar import debug_toolbar_urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app_main.urls',namespace='main')),
    path('user/',include('app_users.urls',namespace='user')),
    path('comments/',include('app_comments.urls',namespace='comment')),
    path('captcha/', include('captcha.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)+ debug_toolbar_urls()

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.BASE_DIR / 'static')

app_base/app_main/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from . import views



app_name = 'main'


urlpatterns = [
     path("",  views.CommentListView.as_view(), name="main"),   
]

app_base/app_users/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from . import views



app_name = 'user'


urlpatterns = [
     path("registration/",  views.RegistrationView.as_view(), name="registr"), 
     path("login/",  views.LoginView.as_view(), name="login"),
     path("logout/",  views.logout, name="logout"), 
]

app_base/app_main/models.py
from django.db import models

# Create your models here.

app_base/app_main/views.py
from django.shortcuts import render
from django.views import View
from app_comments.models import Comment
from django.core.paginator import Paginator
from .order_by import sort_options
from django.core.cache import cache


class CommentListView(View):

    def get(self, request, *args, **kwargs):
        # Получаем сортировку из запроса
        sort_by = request.GET.get('sort_by', '-dateAdded')
        order_by = sort_options.get(sort_by, '-created_at')
        page_number = request.GET.get('page', 1)
        cache_key = f'comments_page_{page_number}_sort_{sort_by}'
       
        comments = cache.get(cache_key)

        if not comments:   
            comments_query = Comment.objects.filter(parent__isnull=True).select_related('user').order_by(order_by)
            paginator = Paginator(comments_query, 5)
            page_obj = paginator.get_page(page_number)

            cache.set(cache_key, page_obj, timeout=600) 
        else:
            page_obj = comments

        return render(request, "app_main/base.html", {
            'comments': page_obj,
            'sort_by': sort_by
        })

app_base/app_main/templates/app_main/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">

<head>
    <!-- Мета-теги -->
    <meta charset="utf-8">
    <meta name="description" content="">
    <meta name="keywords" content="app, landing, corporate, Creative, Html Template, Template">
    <meta name="author" content="web-themes">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Заголовок страницы -->
    <title>recent comment section</title>

    <!-- Подключение CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css"
        crossorigin="anonymous" referrerpolicy="no-referrer" />
        <link href="{% static 'app_main/base.css' %}" rel="stylesheet" type="text/css" />
        

    <link href="{% static 'app_main/lightbox.css' %}" rel="stylesheet" type="text/css" />
</head>

<body>
    {% if user.is_authenticated %}
    <!-- Показываем кнопку, которая открывает модалку комментария -->
    <button class="add-comment-btn" onclick="document.getElementById('commentModal').style.display='block'">Add Comment</button>
{% else %}
    <!-- Показываем кнопку, которая открывает модалку входа -->
    <button class="add-comment-btn" onclick="document.getElementById('loginModal').style.display='block'">Add Comment</button>
{% endif %}

    <!-- Контейнер для всех элементов -->
    <div class="container">
        <!-- Кнопки -->

        <!-- Заголовок раздела комментариев -->
        <h2>Comments</h2>
        <div class="comment-actions">
        {% if not user.is_authenticated %}
        <button class="modal-btn" onclick="openModal('loginModal')">Login</button>
        <button class="modal-btn" onclick="openModal('signupModal')">Registration</button>
        {%else%}
        <form method="post" action="{% url 'user:logout' %}">
            {% csrf_token %}
            <button type="submit">Logout</button>
        </form>
        {% endif %}
        </div>

        <!-- Панель сортировки -->
        <div class="sort-container">
            <form method="get">
                <label for="sort_by">Order by:</label>
                <select name="sort_by" id="sort_by" onchange="this.form.submit()">
                    <option value="-dateAdded" {% if sort_by == "-dateAdded" %}selected{% endif %}>Date Added (newest)</option>
                    <option value="dateAdded" {% if sort_by == "dateAdded" %}selected{% endif %}>Date Added (oldest)</option>
                    <option value="userName" {% if sort_by == "userName" %}selected{% endif %}>User Name</option>
                    <option value="email" {% if sort_by == "email" %}selected{% endif %}>E-mail</option>
                </select>
            </form>
            
        </div>

        <!-- Начало первого комментария -->
       
            <div id="comments-container">
                {% include "app_comments/comments.html" %}
            </div>

        <div class="pagination">
            <span class="step-links">
                {% if comments.has_previous %}
                    <a href="?page=1{% if request.GET.sort_by %}&sort_by={{ request.GET.sort_by }}{% endif %}">&laquo; first</a>
                    <a href="?page={{ comments.previous_page_number }}{% if request.GET.sort_by %}&sort_by={{ request.GET.sort_by }}{% endif %}">previous</a>
                {% endif %}
                <span class="current">
                    Page {{ comments.number }} of {{ comments.paginator.num_pages }}.
                </span>
                {% if comments.has_next %}
                    <a href="?page={{ comments.next_page_number }}{% if request.GET.sort_by %}&sort_by={{ request.GET.sort_by }}{% endif %}">next</a>
                    <a href="?page={{ comments.paginator.num_pages }}{% if request.GET.sort_by %}&sort_by={{ request.GET.sort_by }}{% endif %}">last &raquo;</a>
                {% endif %}
            </span>
        </div>
        <!-- Конец третьего комментария -->

        <!-- Кнопка для добавления комментария -->
       

    </div>

    <!-- Модальное окно для добавления комментария -->
    {% include "app_comments/add_comment.html" %}

    <!-- Модальное окно для ответа на комментарий -->
    {% include "app_comments/form_reply.html" %}


    <!-- Модалка логина -->
    {% include "app_users/login.html" %}


     <!-- Модалка регистрации -->
    {% include "app_users/registr_form.html" %} 


    {% if not request.user.is_authenticated %}
    <script src="{% static 'app_main/auth_form.js' %}"></script>
    {% endif %}

    <!-- Подключение JavaScript -->
    <script src="{% static 'app_main/add_comments.js' %}"></script>
    <script src="{% static "app_main/lightbox-plus-jquery.js" %}"></script>
    <script src="{% static 'app_main/auth.js' %}"></script>
    <script src="{% static 'app_main/base.js' %}"></script>
    <script src="{% static 'app_main/reply_comment.js' %}"></script>
    <script src="{% static 'app_main/js_for_addtags.js' %}"></script>
    <script src="{% static 'app_comments/more_data.js' %}"></script>
    <script src="{% static 'app_main/delete_comment.js' %}"></script>
    <script src="https://unpkg.com/htmx.org@1.9.10"></script>
</body>

</html>