app_base/app_base/urls.py
from argparse import Namespace
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from app_main import views
from debug_toolbar.toolbar import debug_toolbar_urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app_main.urls',namespace='main')),
    path('user/',include('app_users.urls',namespace='user')),
    path('comments/',include('app_comments.urls',namespace='comment')),
    path('captcha/', include('captcha.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)+ debug_toolbar_urls()

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.BASE_DIR / 'static')

app_base/app_comments/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from . import views



app_name = 'comment'


urlpatterns = [
    path('add-comment/', views.AddCommentView.as_view(), name='add_comment'),
    path('reply/', views.AddReplyView.as_view(), name='reply_comment'),
    path('get-replies/<int:comment_id>/', views.CommentRepliesView.as_view(), name='load_replies'),
    path('delete/<int:comment_id>/', views.DeleteCommentView.as_view(), name='delete_comment'),
    
]

app_base/app_comments/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings



class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    parent = models.ForeignKey('self', null=True, blank=True, on_delete=models.CASCADE, related_name='replies')
    text = models.TextField()
    image = models.ImageField(upload_to='comments/', null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f'Comment by {self.user.username} on {self.created_at}'

# Create your models here.

app_base/app_comments/forms.py
from django import forms
from .models import Comment
from django.core.exceptions import ValidationError
from captcha.fields import CaptchaField

class CommentForm(forms.ModelForm):
    text = forms.CharField(widget=forms.Textarea)
    image = forms.FileField(required=False)
    parent_id = forms.IntegerField(widget=forms.HiddenInput, required=False)
    #captcha = CaptchaField() 

    class Meta:
        model = Comment
        fields = ['text', 'image']

    def clean_image(self):
        image = self.cleaned_data.get('image')

        if image:
            file_size = image.size

            if image.name.endswith(('.jpg', '.jpeg', '.png', '.gif')):
                limit = 3 * 1024 * 1024  # 3 MB in bytes для изображений
                if file_size > limit:
                    raise ValidationError("The image size must not exceed 3 MB!!!.")
            elif image.name.endswith('.txt'):
                limit = 100 * 1024  # 100 KB in bytes для текстовых файлов
                if file_size > limit:
                    raise ValidationError("The size of the text file should not exceed 100 KB")
                    
        return image

app_base/app_comments/views.py
import json
import bleach

from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.template.loader import render_to_string
from django.views import View
from django.views.generic import CreateView
from django.core.paginator import Paginator
from django.contrib.auth.mixins import LoginRequiredMixin

from .forms import CommentForm
from .models import Comment
from .utils import convert_special_tags_to_html
from .image_resize import resize_image_pillow

from app_base import settings


class AddCommentView(CreateView):
    """
    Класс для добавления комментария на главную страницу через CreateView.
    """
    model = Comment
    form_class = CommentForm

    def form_valid(self, form):
        """
        Если форма валидна, сохраняем комментарий и возвращаем JSON с HTML.
        """
        comment = form.save(commit=False)
        comment.user = self.request.user

        # 1. Преобразуем специальные теги в HTML
        cleaned_text = convert_special_tags_to_html(comment.text)

        # 2. Очищаем полученный HTML с bleach, разрешая нужные теги
        cleaned_text = bleach.clean(cleaned_text, tags=settings.ALLOWED_TAGS, attributes=settings.ALLOWED_ATTRIBUTES)

        comment.text = cleaned_text

         # 3. Обрабатываем изображение, если оно есть и больше нужных размеров
        if 'image' in self.request.FILES:
            image_file = self.request.FILES['image']
            comment.image = resize_image_pillow(image_file)
            
        comment.save()

        html = render_to_string("app_comments/single_comment.html", {"comment": comment}, request=self.request)

        return JsonResponse({
            "success": True,
            "html": html
        })

    def form_invalid(self, form):
        """
        Если форма невалидна, отправляем ошибки в JSON.
        """
        errors = {}
        for field, error in form.errors.items():
            errors[field] = error
        return JsonResponse({"success": False, "errors": json.dumps(errors)})





class AddReplyView(CreateView):
    """
    Класс для добавления ответа на комментарий.
    """
    model = Comment
    form_class = CommentForm

    def form_valid(self, form):
        """
        Если форма валидна, сохраняем ответ и возвращаем JSON с HTML.
        """
        parent_id = self.request.POST.get('parent_id')
        
        try:
            parent_comment = Comment.objects.get(id=parent_id)
        except Comment.DoesNotExist:
            return JsonResponse({"success": False, "errors": {"parent": ["Родительский комментарий не найден."]}}, status=400)

        # Создаём новый ответ
        reply = form.save(commit=False)
        reply.user = self.request.user
        cleaned_text = convert_special_tags_to_html(reply.text)
        cleaned_text = bleach.clean(cleaned_text, tags=settings.ALLOWED_TAGS, attributes=settings.ALLOWED_ATTRIBUTES) #фильтруем теги
        reply.text = cleaned_text

        reply.parent_id = parent_id
        reply.save()
        # Получаем текст родительского комментария
        parent_text = parent_comment.text
        clean_parent_text = bleach.clean(parent_text)
        # Рендерим HTML только что добавленного ответа
        html = render_to_string("app_comments/single_comment.html", {"comment": reply}, request=self.request)

        return JsonResponse({
            "success": True,
            "html": html,
            "parent_id": parent_id,
            "parent_text": clean_parent_text
        })

    def form_invalid(self, form):
        """
        Если форма невалидна, отправляем ошибки в JSON.
        """
        errors_dict = {}
        for field, error_list in form.errors.items():
            errors_dict[field] = [str(e) for e in error_list]
        return JsonResponse({"success": False, "errors": errors_dict}, status=400)



class CommentRepliesView(View):


    def get(self, request, comment_id):
        parent_comment = get_object_or_404(Comment, id=comment_id)
        replies = parent_comment.replies.all().order_by('-created_at')
        page_number = int(request.GET.get('page', 1))
        paginator = Paginator(replies, 8)  # Количество ответов на странице
        page_obj = paginator.get_page(page_number)
        initial_load = request.GET.get('initial_load', False)

        context = {
            'replies': page_obj,
            'parent_id': comment_id,
            'page_number': page_number,
        }

        return render(request, 'app_comments/replies_list.html', context)

            


class DeleteCommentView(LoginRequiredMixin, View):
    def post(self, request, comment_id):
        try:
            comment = get_object_or_404(Comment, id=comment_id)
            if request.user == comment.user or request.user.is_staff:
                comment.delete()
                return JsonResponse({"success": True, "message": "Comment successfully deleted."})
            else:
                return JsonResponse({"success": False, "error": "You do not have permission to delete this comment."}, status=403)
        except Exception as e:
            return JsonResponse({"success": False, "error": f"An error occurred while deleting the comment.{e}"}, status=500)
















#def add(request):
    #form = CommentForm()
    #if request.method == 'POST':
        #form = CommentForm(request.POST, request.FILES)
        #if form.is_valid():
            #comment = form.save(commit=False)
            #comment.user = request.user  
            #comment.save()

            # Рендерим HTML для нового комментария
            #html = render_to_string("app_comments/single_comment.html", {"comment": comment})
            #return JsonResponse({"success": True, "html": html})

        #else:
            # Если форма не валидна, отправляем ошибки
            #errors = {}
            #for field, error in form.errors.items():
                #errors[field] = error
            #return JsonResponse({"success": False, "errors": json.dumps(errors)})








#def add_reply(request):
    #if request.method == 'POST':
        #form = CommentForm(request.POST, request.FILES)
        #if form.is_valid():
            #parent_id = request.POST.get('parent_id')
            #try:
                #parent_comment = Comment.objects.get(id=parent_id)
            #except Comment.DoesNotExist:
                #return JsonResponse({"success": False, "errors": {"parent": ["Родительский комментарий не найден."]}})

            #reply = form.save(commit=False)
            #reply.user = request.user
            #reply.parent_id = parent_id
            #reply.save()

            # Отримуємо текст БЕЗПОСЕРЕДНЬОГО батьківського коментаря
            #parent_text = parent_comment.text

            # Рендерим HTML только что добавленного ответа
            #html = render_to_string("app_comments/single_comment.html", {"comment": reply})
            #return JsonResponse({"success": True, "html": html, "parent_id": parent_id, "parent_text": parent_text})
        #else:
            #errors_dict = {}
            #for field, error_list in form.errors.items():
                #errors_dict[field] = [str(e) for e in error_list]
            #return JsonResponse({"success": False, "errors": errors_dict})
    #return JsonResponse({"success": False, "errors": ["Недопустимый метод запроса."]})

app_base/app_comments/templates/app_comments/add_comment.html
<div id="commentModal" class="modal">
    <div class="modal-content">
        <span class="close" onclick="this.parentElement.parentElement.style.display='none'">&times;</span>
        <h2>Add a comment</h2>
        <div id="formErrors" style="color: red;"></div>
        <form id="commentForm" action="{% url "comment:add_comment" %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="comment-editor">
                
                <textarea rows="4" placeholder="Your comment..." name="text" id="commentText" required onkeyup="previewComment()"></textarea>
            </div>
            <div class="editor-buttons">
                <button type="button" class="editor-button" onclick="insertTag('[i]', '[/i]', 'commentText')">[i]</button>
                <button type="button" class="editor-button" onclick="insertTag('[strong]', '[/strong]', 'commentText')">[strong]</button>
                <button type="button" class="editor-button" onclick="insertTag('[code]', '[/code]', 'commentText')">[code]</button>
            </div>
            <div class="comment-preview">
                <h3>Preview:</h3>
                <div id="commentPreviewContent"></div>
            </div>

            <div class="file-upload-wrapper">
                <div id="comment_file_error" class="error-message"></div>

                <label for="fileInput" class="custom-file-upload">
                    📎Select file
                </label>
                <input type="file" id="fileInput" name="image" accept=".jpg,.jpeg,.png,.gif,.txt">

                <div class="file-info">
                    <span id="file-name" class="file-name">File not selected</span>
                    <a type="" id="remove-file" class="remove-file" style="display:none;">✖</a>
                </div>
            </div>
            <div id="previewContainer"></div>
            <button type="submit">Send</button>
        </form>

    </div>
</div>

app_base/app_comments/templates/app_comments/comment_list.html
{% for comment in comments %}
    {% if comment.parent is None %}
        {% include "app_comments/single_comment.html" with comment=comment %}
    {% endif %}
{% endfor %}

app_base/app_comments/templates/app_comments/comments.html
{% load static %}

<div id="comments-container">
    {% for comment in comments %}
        {% if comment.parent is None %}
            {% include "app_comments/single_comment.html" with comment=comment %}
        {% endif %}
    {% endfor %}
</div>

app_base/app_comments/templates/app_comments/form_reply.html
<div id="replyModal" class="modal">
    <div class="modal-content">
        <span class="close" onclick="this.parentElement.parentElement.style.display='none'">&times;</span>
        <h2>Reply to comment</h2>
        <form id="replyForm" action="{% url "comment:reply_comment" %}" method="post" enctype="multipart/form-data">
            <div id="reply_file_error" class="error-message"></div>
            {%csrf_token%}
            <textarea rows="4" placeholder="your answer..." name="text" id="replyText" minlength="2" onkeyup="previewReply()"></textarea>
            <input type="hidden" name="parent_id" id="replyParentId">
            <div class="editor-buttons">
                <button type="button" class="editor-button" onclick="insertTag('[i]', '[/i]', 'replyText')">[i]</button>
                <button type="button" class="editor-button" onclick="insertTag('[strong]', '[/strong]', 'replyText')">[strong]</button>
                <button type="button" class="editor-button" onclick="insertTag('[code]', '[/code]', 'replyText')">[code]</button>
            </div>
            <div class="reply-preview">
                <h3>Preview:</h3>
                <div id="replyPreviewContent"></div>
            </div>
            
            <div class="file-upload-wrapper">
                <label for="replyFileInput" class="custom-file-upload">
                    📎Select file
                </label>
                <input type="file" id="replyFileInput" name="image" accept=".jpg,.jpeg,.png,.gif,.txt">
                <div class="file-info">
                    <span id="reply-file-name" class="file-name">File not selected</span>
                    <a id="remove-reply-file" class="remove-file" style="display:none;">✖</a>
                </div>
            </div>
            <div id="previewContainerReply"></div> 
            <button type="submit">Send reply</button>
        </form>
    </div>
</div>

app_base/app_comments/templates/app_comments/replies_list.html
<div id="replies-list-inner-{{ parent_id }}">
    {% for reply in replies %}
        {% include "app_comments/single_reply.html" with comment=reply %}
    {% empty %}
        <p class="no-replies">No replies yet.</p>
    {% endfor %}

    {% if replies.has_next %}
        <div hx-get="{% url 'comment:load_replies' comment_id=parent_id %}?page={{ replies.next_page_number }}"
             hx-target="#replies-list-inner-{{ parent_id }}"
             hx-swap="beforeend"
             class="load-more-container">
            <button class="load-more-replies-btn">Load more</button>
          
        </div>
    {% endif %}
</div>

app_base/app_comments/templates/app_comments/single_comment.html
{% load filters %}
<div class="comment-card" id="comment-{{ comment.id }}" data-comment-id="{{ comment.id }}">
    <div class="comment-header">
        <a href="{% if comment.user.avatar %}{{ comment.user.avatar.url }}{% else %}/media/avatars/avatar.png{% endif %}" data-lightbox="models" data-title="Это аватар пользователя">
            <img src="{% if comment.user.avatar %}{{ comment.user.avatar.url }}{% else %}/media/avatars/avatar.png{% endif %}" alt="аватар" class="thumbnail">
        </a>
        <div class="comment-meta">{{ comment.user.username }} | <span>{{ comment.created_at|date:"d M Y" }}</span></div>
    </div>
    <div class="comment-text">{{ comment.text|safe }}</div>

    {% if comment.image %}
    {% if comment.image.name|endswith:".txt" %}
        <div class="comment-file">
            <a href="{{ comment.image.url }}" download>
                📄Download text file
            </a>
        </div>
    {% else %}
        <div class="comment-image">
            <a href="{{ comment.image.url }}" data-lightbox="models" data-title="Это изображение в комментарии">
                <img src="{{ comment.image.url }}" alt="Изображение в комментарии" class="comment-img">
            </a>
        </div>
    {% endif %}
{% endif %}


    <div class="comment-actions">
        {% if user.is_authenticated %}
        <button class="reply-btn" data-parent-id="{{ comment.id }}">Reply</button>
        {% else %}
       <!-- Если не авторизован — открываем модалку входа -->
            <button class="" onclick="document.getElementById('loginModal').style.display='block'">Reply</button>
        {% endif %}
        {% if comment.replies.exists%}
        <button hx-get="{% url 'comment:load_replies' comment_id=comment.id %}?page=1&initial_load=true"
                hx-target="#replies-container-{{ comment.id }}"
                hx-swap="innerHTML"
                class="show-replies-btn" onclick="toggleReplies(this)">
            Show replies
            {% if comment.replies.count > 0 %}
                ({{ comment.replies.count }})
            {% endif %}
        </button>
        {% endif %}
        
    </div>

    <div id="replies-container-{{ comment.id }}" style="display: none;">
        </div>
</div>

app_base/app_comments/templates/app_comments/single_reply.html
<div class="comment-card" id="comment-{{ comment.id }}" data-comment-id="{{ comment.id }}">
    <div class="comment-header">
        <a href="{% if comment.user.avatar %}{{ comment.user.avatar.url }}{% else %}/media/avatars/avatar.png{% endif %}" data-lightbox="models" data-title="Это аватар пользователя">
            <img src="{% if comment.user.avatar %}{{ comment.user.avatar.url }}{% else %}/media/avatars/avatar.png{% endif %}" alt="аватар" class="thumbnail">
        </a>
        <div class="comment-meta">{{ comment.user.username }} | <span>{{ comment.created_at|date:"d M Y" }}</span></div>
    </div>

    {% if comment.parent %}
        <blockquote class="reply-to-comment">{{ comment.parent.text|safe }}</blockquote>
    {% endif %}

    <div class="comment-text">{{ comment.text|safe }}</div>

    {% if comment.image %}
        <div class="comment-image">
            <a href="{{ comment.image.url }}" data-lightbox="models" data-title="Это изображение в ответе">
                <img src="{{ comment.image.url }}" alt="Изображение в ответе" class="comment-img">
            </a>
        </div>
    {% endif %}

    <div class="comment-actions">
        {% if user.is_authenticated %}
        <button class="reply-btn" data-parent-id="{{ comment.id }}">Reply</button>
        {% else %}
       <!-- Если не авторизован — открываем модалку входа -->
            <button class="" onclick="document.getElementById('loginModal').style.display='block'">Reply</button>
        {% endif %}
        {% if comment.replies.exists %}
            <button
                hx-get="{% url 'comment:load_replies' comment_id=comment.id %}?page=1&initial_load=true"
                hx-target="#replies-container-{{ comment.id }}"
                hx-swap="innerHTML"
                class=""
                onclick="toggleReplies(this)">
                Show answers ({{ comment.replies.count }})
            </button>
        {% endif %}
        
    </div>

    <div class="replies" id="replies-container-{{ comment.id }}" style="display: none;"></div>
</div>