app_base/app_base/urls.py
from argparse import Namespace
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from app_main import views
from debug_toolbar.toolbar import debug_toolbar_urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app_main.urls',namespace='main')),
    path('user/',include('app_users.urls',namespace='user')),
    path('comments/',include('app_comments.urls',namespace='comment')),
    path('captcha/', include('captcha.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)+ debug_toolbar_urls()

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.BASE_DIR / 'static')

app_base/app_users/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from . import views



app_name = 'user'


urlpatterns = [
     path("registration/",  views.RegistrationView.as_view(), name="registr"), 
     path("login/",  views.LoginView.as_view(), name="login"),
     path("logout/",  views.logout, name="logout"), 
]

app_base/app_users/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser
from django.contrib.auth import authenticate
from django.core.exceptions import ValidationError

class CustomUser(AbstractUser):
    username = models.CharField(max_length=100, unique=False,verbose_name='username')
    email = models.EmailField(max_length=100,unique=True,verbose_name='email')
    homepage = models.URLField(max_length=200,verbose_name='home-page')
    avatar = models.ImageField(upload_to='avatars/', blank=True, null=True)  # Аватар пользователя

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']
    

    class Meta:
        db_table = 'user'
        verbose_name = 'users'
        verbose_name_plural = 'users'

    def __str__(self):
        return self.email

app_base/app_users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm,UserCreationForm
from django.contrib.auth import get_user_model
from .models import CustomUser
from django.contrib.auth import authenticate
from django.core.exceptions import ValidationError





class UserRegisterForm(UserCreationForm):
    avatar = forms.ImageField(
        required=False, 
        label="Avatar (Optional)"
    )
    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'homepage', 'password1', 'password2', 'avatar']

    def clean_avatar(self):
        avatar = self.cleaned_data.get('avatar')
        
        if avatar:
            file_size = avatar.size
            limit = 3 * 1024 * 1024  # 3 MB in bytes
            if file_size > limit:
                raise ValidationError("The file size must not exceed 3 MB.")
        
        return avatar




class UserLoginForm(forms.Form):
    email = forms.EmailField(label="Email", max_length=100)
    password = forms.CharField(widget=forms.PasswordInput, label="Password")

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super().__init__(*args, **kwargs)

    def clean(self):
        cleaned_data = super().clean()
        email = cleaned_data.get('email')
        password = cleaned_data.get('password')
        user = authenticate(request=self.request, email=email, password=password)
        if not user:
            raise ValidationError("Invalid email or password.")  # Ошибка попадёт в non_field_errors
        self.user = user
        return cleaned_data

    def get_user(self):
        return self.user

app_base/app_users/views.py
from django.shortcuts import redirect
from django.views.generic.edit import FormView
from django.views import View
from django.http import JsonResponse, HttpResponseRedirect, HttpRequest, HttpResponse
from django.urls import reverse_lazy, reverse
from django.contrib.auth import authenticate, login as auth_login
from .forms import UserRegisterForm, UserLoginForm
from django.contrib import auth, messages
from django.contrib.auth.decorators import login_required

class RegistrationView(FormView):
    """
    Вью для регистрации пользователя.
    Использует Django FormView для обработки формы регистрации.
    """

    form_class = UserRegisterForm  # Форма, используемая для регистрации
    success_url = reverse_lazy('main:main')  # URL для перенаправления после успешной регистрации

    def form_valid(self, form: UserRegisterForm) -> JsonResponse:
        """
        Метод вызывается при успешной валидации формы.
        Сохраняет пользователя и возвращает JSON-ответ об успехе.
        """
        user = form.save()  # Сохраняем пользователя в БД
        messages.success(self.request, 'Registration was successful please login ')
        return JsonResponse({
            'success': True,
            'message': 'Registration successful',
            'redirect': self.success_url  # URL для редиректа 
        }, status=200)

    def form_invalid(self, form: UserRegisterForm) -> JsonResponse:
        """
        Метод вызывается при неуспешной валидации формы.
        Возвращает JSON с ошибками формы.
        """
        return JsonResponse({'errors': form.errors.as_json()}, status=400)



class LoginView(View):
    """
    Вью для авторизации пользователя.
    Обрабатывает POST-запросы с формой входа.
    """

    def post(self, request: HttpRequest, *args, **kwargs) -> HttpResponse:
        """
        Принимает данные формы, валидирует их,
        аутентифицирует пользователя и логинит его.
        В случае ошибки возвращает JSON с ошибками.
        """
        form = UserLoginForm(request.POST)

        if form.is_valid():
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']

            # Пытаемся аутентифицировать пользователя
            user = authenticate(request, email=email, password=password)

            if user:
                # Успешная аутентификация — логиним пользователя
                auth_login(request, user)
                messages.success(request, "You have successfully logged in!")
                return HttpResponseRedirect(reverse('main:main'))

        # Если форма невалидна — возвращаем ошибки
        return JsonResponse({'errors': form.errors.as_json()}, status=400)





@login_required
def logout(request):
    auth.logout(request)
    return redirect(reverse('main:main'))

app_base/app_users/templates/app_users/login.html
<!-- Модалка логина -->
<div id="loginModal" class="modal-overlay" onclick="outsideClick(event, 'loginModal')">
    <div class="modal-container">
        <span class="modal-close" onclick="closeModal('loginModal')">&times;</span>
        <div class="modal-wrapper">
         
            {% if messages %}
            <ul class="messages" id="message-container">
              {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                  {{ message }}
                </li>
              {% endfor %}
            </ul>
            {% else %}
            <div id="modal-info-message" class="info-message">
              To write comments you need to log in or register.
          </div>
            {% endif %}
            <h1>Login</h1>
            
            <form action="" method="post" id="login-form" data-url="{% url 'user:login' %}" class="modal-form">
                {% csrf_token %}
                <input type="email" class="modal-input" name="email" placeholder="email" required />
                
                <input type="password" name="password" class="modal-input" placeholder="password" autocomplete="new-password"
                    required />
                    <div class="non-field-errors" style="color: red; margin-top: 10px;"></div>
                <button class="modal-submit" type="submit">Sign In</button> 
            </form>
            <div class="modal-links">
                Not a member? <a href="#" onclick="switchModal('loginModal', 'signupModal')">register now</a>
            </div>
        </div>
    </div>
</div>

app_base/app_users/templates/app_users/registr_form.html
{% load static %}
<!-- Модалка регистрации -->
<div id="signupModal" class="modal-overlay" onclick="outsideClick(event, 'signupModal')">
    <div class="modal-container">
        <span class="modal-close" onclick="closeModal('signupModal')">&times;</span>
        <div class="modal-wrapper">
            <h1>Sign Up</h1>
            <form action="{% url "user:registr" %}"  method="post" class="modal-form" enctype="multipart/form-data"  data-js-form>
                {% csrf_token %}
                <input type="text" for="username" id="name" name="username" class="modal-input" placeholder="username"
                value="{% if form.username.value %}{{form.username.value}}{% endif %}" required/>
                <span id="name_error" class="field__errors"></span>

                <input type="email" for="email" id="email" class="modal-input" name="email" placeholder="email" required />
                <span id="email_error" class="field__errors"></span>
                <span class="field-error" id="email_error" style="color: red;"></span>

                <input type="homepage" id="homepage" class="modal-input" name="homepage" placeholder="homepage"/>
                <span id="homepage_error" class="field__errors" style="color: red; font-size: 0.8em; display: block;"></span>

                <input type="password" for="password1" id="password" name='password1' class="modal-input" placeholder="password"
                    autocomplete="new-password" required/>
                <span id="password_error" class="field__errors"></span>

                <input type="password" for="password2" id="confirm_password" name='password2' class="modal-input" placeholder="re-enter-password" required/>
                <span id="confirm_password_error" class="field__errors"></span>

                <!-- Поле для загрузки аватара -->
                <div class="file-upload-wrapper">
                    <span class="field__errors" id="avatar_error"></span>

                    <label for="avatarInput" class="custom-file-upload">
                        📎 Select avatar
                    </label>
                    <input type="file" id="avatarInput" name="avatar" accept="image/*"/>

                    <div class="file-info">
                        <span id="avatar-file-name" class="file-name">File not selected</span>
                        <a id="remove-avatar-file" class="remove-file" style="display:none;" href="#">✖</a>
                    </div>
                </div>

                <!-- Контейнер для предпросмотра изображения -->
                <div id="previewContainerAvatar"></div>

                <button class="modal-submit" type="submit">Sign Up</button>
            </form>
            <div class="modal-links">
                Already a member? <a href="#" onclick="switchModal('signupModal', 'loginModal')">login here</a>
            </div>
        </div>
    </div>
</div>

    